name: ramachandraw

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
    
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          pytest --cov=ramachandraw
          coverage lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.1.0
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          file: coverage.lcov
